---
title: "HIV fitness figures"
format: html
execute: 
  message: false
  warning: false
  echo: false
---

```{r, load_libraries}
# Load libraries
library(tidyverse)
library(phytools)
library(ape)
library(ggtree)
library(treeio)
library(rstatix)
library(ggpubr)
library(reshape2)
library(scales)
library(cowplot)
library(patchwork)
library(knitr)

# Set plotting theme
theme_set(theme_classic() + 
            theme(strip.background = element_rect(color = 'white'), 
                  strip.text.y = element_text(angle = 0),
                  panel.border = element_rect(color = 'black', fill = NA, linewidth = 0.5), 
                  axis.line = element_blank(),
                  text = element_text(size = 16)))

opts_chunk$set(dpi = 300, fig.retina = 2)
```

```{r, load_data}
# Read in metadata
metadat <- read_csv('empirical_data/metadata/sample_info.csv') %>% 
  rename(id_orig = aln_ids) %>% 
  # IDs from original manuscripts
  mutate(id = case_when(id_orig == '10137+1+B' ~ 'P3',
                            id_orig == '10138+1+B' ~ 'P8',
                            id_orig == '105692+197+B' ~ 'F4',
                            id_orig == '105693+202+B' ~ 'F8',
                            id_orig == '105696+207+B' ~ 'F2',
                            id_orig == '105698+280+B' ~ 'F1',
                            id_orig == '10586+1+B' ~ 'P9',
                            id_orig == '13889+1+B' ~ 'P2',
                            id_orig == '820+1+B' ~ 'P1',
                            id_orig == '821+1+B' ~ 'P5',
                            id_orig == '822+1+B' ~ 'P6',
                            id_orig == '824+1+B' ~ 'P7',
                            id_orig == '825+1+B' ~ 'P11'),
       id = factor(id, levels = c('P1', 'P2', 'P3', 'P5', 'P6', 'P7', 'P8', 'P9', 'P11', 'F1', 'F2', 'F4', 'F8'))) %>%
  drop_na() 
  
id_conversion <- metadat %>% 
  select(id_orig, id)

# Accession numbers in each timepoint
seqs_in_timepoints <- metadat %>% 
   select(id, gen=timepoints, accession=seq_in_timepoint) %>% 
   separate_rows(c(gen, accession), sep = "(?<!^)-", convert = TRUE) %>%  # ignore dashes at beginning of row (negative lookbehind) 
   separate_rows(accession) %>% 
  mutate(gen = ifelse(gen < 0, 0, gen))

# Empirical alignments
fastas <- list.files('empirical_data/empirical_alns_trs', pattern = 'B.fasta', full.names = TRUE)
alns <- lapply(fastas, read.FASTA)
names(alns) <- gsub('empirical_data/empirical_alns_trs/|.fasta', '', fastas)

# Empirical distances to reference
dists_to_ref_real <- lapply(alns, function(x){
  d <- dist.dna(x, model = 'raw', pairwise.deletion = TRUE, as.matrix = TRUE)
  d <- d["Consensus_Subtype_B",colnames(d) != "Consensus_Subtype_B"]
  names(d) <- sapply(strsplit(names(d), '_'), function(x) x[4])
  d %>% enframe(name = 'accession', value = 'dist')
}) %>% bind_rows() %>% 
  inner_join(seqs_in_timepoints) %>% 
  mutate(censored = id == 'P2' & gen > 3000) %>% 
  group_by(id, gen) %>% 
  mutate(mean_dist = mean(dist)) %>% 
  group_by(id) %>% 
  mutate(min_gen = gen[which.min(mean_dist)]) %>% 
  select(id, gen, dist, mean_dist, min_gen, censored)

# Simulated distances to reference
dists_to_ref_sim <- read_csv('simulations/summaries/dists_to_ref.csv') %>% 
  separate(filename, into = c('id_orig', 'maxepi', 'repcost', 'conscost', 'run', 'rep', 'dist'), sep = '_') %>% 
  mutate(id_orig = gsub('.*/', '', id_orig),
         maxepi = as.numeric(gsub('maxepi', '', maxepi)),
         repcost = as.numeric(gsub('repcost', '', repcost)),
         conscost = as.numeric(gsub('conscost', '', conscost)),
         run = as.numeric(gsub('run', '', run)),
         rep = as.numeric(gsub('rep', '', rep))) %>% 
  left_join(id_conversion) %>% 
  select(-c(dist, id_orig))
```



# Results

## Simulations

### Total number of simulations

```{r, n_sims}
dists_to_ref_sim %>% 
  select(id, maxepi, repcost, conscost, run, rep) %>% 
  distinct() %>% 
  nrow()
```

### Distance to reference


```{r, dist_to_ref_sim, fig.width=10, fig.height=4}
dists_to_ref_sim %>% 
  ggplot(aes(x = gen/365, y = mean_dist_to_ref, col = factor(maxepi), shape = factor(conscost))) +
  facet_grid(~paste(repcost)) +
  geom_smooth(aes(linetype = factor(conscost, levels = c(0.99, 0))), se = FALSE) +
  scale_color_viridis_d(option = 'G') +
  scale_shape_manual(values = c(1, 19)) +
  scale_x_continuous(breaks = breaks_pretty()) +
  coord_fixed(ratio = 60) +
  labs(x = 'Years post-infection', y = 'Mean distance to\nreplicative reference', col = 'Immune\ncost', linetype = 'Purifying\ncost') +
  guides(linetype = guide_legend(override.aes = list(col = 'black'))) +
  theme(legend.position = 'bottom', 
        strip.placement = "outside",
        legend.title = element_text(hjust = 1)) 
```

```{r dist_to_ref_sim_supp, fig.width=10, fig.height=12}
dists_to_ref_sim %>% 
  filter(conscost == 0.99) %>%
  ggplot(aes(x = gen/365, y = mean_dist_to_ref, col = factor(maxepi))) +
  facet_grid(id~repcost, scales = 'free') +
  geom_smooth(se = FALSE) +
  geom_point(data = dists_to_ref_real %>% 
    group_by(id, gen) %>% 
    summarize(mean_dist_to_ref_real = mean(dist)),
  aes(y = mean_dist_to_ref_real, shape = 'Empirical\nvalue'), col = 'black') +
  scale_color_viridis_d(option = 'G') +
  labs(x = 'Years post-infection', y = 'Mean distance to\nreplicative reference', col = 'Immune\ncost', shape = '')
```

## Fitness vs. distance to reference

```{r consensus_fitness, fig.width=7, fig.height=4}
fit <- read_csv('empirical_data/competition_assays/data/mean_relative_fitness.csv') %>% 
  mutate(isolate_name = gsub('_', '', isolate_name))

pol <- read.FASTA('empirical_data/competition_assays/alns/pol_aligned.fasta')
env <- read.FASTA('empirical_data/competition_assays/alns/env_aligned.fasta')

pol_dists <- dist.dna(pol, model = 'raw', pairwise.deletion = TRUE, as.matrix = TRUE)
pol_dists[lower.tri(pol_dists, diag = TRUE)] <- NA
env_dists <- dist.dna(env, model = 'raw', pairwise.deletion = TRUE, as.matrix = TRUE)
env_dists[lower.tri(env_dists, diag = TRUE)] <- NA

pol_dists_df <- pol_dists %>% 
  melt(value.name = 'pol_dist') %>% 
  drop_na() %>% 
  mutate(con1 = ifelse(grepl('CON', Var1), 'yes', 'no'),
         con2 = ifelse(grepl('CON', Var2), 'yes', 'no'),
         subtype1 = ifelse(grepl('CON', Var1), gsub('CON_|\\(.*', '', Var1), gsub('\\..*', '', Var1)),
         subtype2 = ifelse(grepl('CON', Var2), gsub('CON_|\\(.*', '', Var2), gsub('\\..*', '', Var2))) %>% 
  filter(subtype1 == subtype2 & con1 != con2 & !grepl('HXB2', Var1) & !grepl('HXB2', Var2)) %>%
  separate(Var2, sep = '\\.', into = c('subtype', 'location', 'year', 'isolate_name', 'accession_pol')) %>% 
  mutate(Var1 = gsub('_Pol', '', Var1))

env_dists_df <- env_dists %>% 
  melt(value.name = 'env_dist') %>% 
  drop_na() %>% 
  mutate(con1 = ifelse(grepl('CON', Var1), 'yes', 'no'),
         con2 = ifelse(grepl('CON', Var2), 'yes', 'no'),
         subtype1 = ifelse(grepl('CON', Var1), gsub('CON_|\\(.*', '', Var1), gsub('\\..*', '', Var1)),
         subtype2 = ifelse(grepl('CON', Var2), gsub('CON_|\\(.*', '', Var2), gsub('\\..*', '', Var2))) %>% 
  filter(subtype1 == subtype2 & con1 != con2 & !grepl('HXB2', Var1) & !grepl('HXB2', Var2)) %>%
  separate(Var2, sep = '\\.', into = c('subtype', 'location', 'year', 'isolate_name', 'accession_env')) %>% 
  mutate(Var1 = gsub('_Env', '', Var1))

summary_df <- full_join(pol_dists_df, env_dists_df) %>% 
  full_join(fit)

summary_df %>% 
  filter(subtype == 'B') %>% 
  drop_na() %>% 
  rename(pol=pol_dist, env=env_dist) %>% 
  pivot_longer(c(pol, env), names_to = 'gene', values_to = 'dist') %>% 
  mutate(gene = factor(gene, levels = c('pol', 'env'))) %>% 
  rowwise() %>% 
  mutate(mean_W = (inter_group_W + intra_group_W)/2) %>% 
  ungroup() %>% 
  ggplot(aes(x = dist, y = mean_W)) +
  facet_grid(~gene, scales = 'free') +
  geom_point(size = 3, alpha = 0.75) +
  geom_smooth(span = 2, col = 'black') +
  stat_cor(method = 'spearman', cor.coef.name = "rho", label.x.npc = 0.5, label.y = 2.5) +
  labs(x = 'Distance to consensus sequence', y = 'Relative replicative fitness')
```

## Within-host data


### Distance to reference over time

```{r slopes}
dists_to_ref_real
# Simple approach
slopes <- dists_to_ref_real %>%
  mutate(yr = gen/365) %>% 
  filter(!censored) %>%
  group_by(id) %>%
  summarize(start_dist = mean(dist[gen == min(gen)]),
            slope = coef(lm(dist ~ yr))[2]) %>% 
  ungroup() 

slopes %>% 
  summarize(mean_slope = mean(slope),
            min_slope = min(slope),
            max_slope = max(slope))
```

```{r}
dists_to_ref_real %>% 
  ungroup() %>% 
  summarize(mean_dist = mean(dist),
            min_dist = min(dist),
            max_dist = max(dist))
```


```{r pvals}
min_dist <- dists_to_ref_real %>% 
  filter(!censored) %>% 
  group_by(id) %>% 
  filter(gen == min_gen) %>% 
  select(-c(gen, min_gen)) %>%  
  mutate(type = 'min')

max_dist_left <- dists_to_ref_real %>% 
  filter(!censored) %>% 
  group_by(id) %>% 
  filter(gen < min_gen) %>% 
  mutate(mean_dist = mean(dist)) %>% 
  slice_max(mean_dist) %>%
  select(-c(gen, min_gen, mean_dist)) %>%  
  mutate(type = 'max_left')

max_dist_right <- dists_to_ref_real %>% 
  filter(!censored) %>% 
  group_by(id) %>% 
  filter(gen > min_gen) %>% 
  mutate(mean_dist = mean(dist)) %>% 
  slice_max(mean_dist) %>% 
  select(-c(gen, min_gen, mean_dist)) %>%  
  mutate(type = 'max_right')

pvals <- min_dist %>% 
  bind_rows(max_dist_left) %>% 
  bind_rows(max_dist_right) %>% 
  group_by(id) %>% 
  wilcox_test(formula = dist ~ type,
              p.adjust.method = 'holm', ref.group = 'min', alternative = 'less')

pvals
```

```{r dist_to_ref_real, fig.width=10, fig.height=5}
dists_to_ref_real %>% 
  mutate(id = factor(id, levels = c(paste0('P', c(8, 9, 11)), paste0('F', c(1, 2, 4, 8)), paste0('P', c(1,2,3,5,6,7))))) %>%
  ggplot(aes(x = gen/365, y = dist)) +
  facet_wrap(~id, nrow = 2, drop = FALSE, dir = 'lb') +
  geom_point(aes(shape = censored), alpha = 0.25, col = 'grey', show.legend = FALSE) +
  scale_shape_manual(values = c(19, 1)) +
  geom_smooth(data = dists_to_ref_real %>% filter(!censored), method = 'loess', se = FALSE, color = 'grey20') +
  geom_vline(aes(xintercept = min_gen/365, linetype = 't_min')) + 
  scale_linetype_manual(values = c('dotted'), 
                      labels = expression(t[min])) +
  theme(aspect.ratio = 1,
        legend.position = c(0.92 , 0.85), #c(0.935 , 0.3),
        legend.box.background = element_rect(fill = NA, color = NA),
        legend.box.margin = margin(55,0,40,2),
        ) +
  labs(x = 'Years post-infection', y = 'Distance to\nreplicative reference', linetype = '') +
  geom_text(data = pvals %>% 
              left_join(dists_to_ref_real %>% select(id, min_gen) %>% distinct()) %>% 
              mutate(p.adj.signif = case_when(group2 == 'max_right' ~ str_pad(p.adj.signif, width = 4, side = "right", pad = " "),
                                              group2 == 'max_left' ~ str_pad(p.adj.signif, width = 4, side = "left", pad = " "))) %>% 
              group_by(id, min_gen) %>% 
              summarize(lab = ifelse(n() == 2, paste0(p.adj.signif, collapse = ' '), paste0('     ', p.adj.signif))), 
            aes(label = lab, x = min_gen/365+0.5), y = 0.135, hjust = 0.57, size = 3)
```


### Phylogenies with reference

```{r load_phylogenies}
# Read in trees and root them
tr_paths <- list.files('empirical_data/empirical_alns_trs/iqtree', pattern = 'treefile', full.names = TRUE)
trees <- lapply(tr_paths, read.tree)
names(trees) <- gsub('empirical_data/empirical_alns_trs/iqtree/|.fasta.treefile', '', tr_paths)

ids <- id_conversion %>% select(id_orig, id) %>% deframe()

names(trees) <- ids[names(trees)]
trees <- trees[levels(ids)]

seqs_first_timepoint <- lapply(names(trees), function(x){
  first_timepoint <- metadat %>% 
    filter(id == x) %>% 
    pull(seq_in_timepoint) %>% 
    gsub('-.*', '', .) %>% 
    strsplit('\\+') %>% 
    unlist()
})
names(seqs_first_timepoint) <- names(trees)

trees_rooted <- lapply(names(trees), function(x){
  tr_sub <- trees[[x]] %>%
    unroot() 
  first_timepoint <- seqs_first_timepoint[[x]]
  og_tiplabs <- sapply(first_timepoint, function(y) tr_sub$tip.label[grepl(y, tr_sub$tip.label)])
  tr_sub %>% reroot(node = getMRCA(tr_sub, og_tiplabs))
})
names(trees_rooted) <- names(trees)
```

```{r t2dist_fn}
t2dist<-function(t,cid){
  ntip<-length(t$tip.label)
  nnode<-Nnode(t)
  root_node<-ntip+1
  intnodes<-root_node:(nnode+ntip)
  d<-dist.nodes(t)
  tf_c<-t$edge[,2]==cid
  if (sum(tf_c)!=1){
    stop('Could not find an unambiguous reference (consensus) branch')
  }
  anc_c<-t$edge[tf_c,1]
  fb<-max(d[setdiff(intnodes,anc_c),root_node])
  tf<-d[,root_node]==fb
  b<-which(tf)
  b<-setdiff(b,anc_c)
  if(length(b)==0){
    stop('Could not find B node')
  }
  if(length(b)>1){
    warning('More than one B node possible. Ties were broken randomly')
    b<-b[1]
  }
  j<-getMRCA(t,c(b,cid))
  fj<-d[j,root_node]
  return(c(fj,fb)) 
}
```


```{r load_bayes}
load('empirical_data/mrbayes/13_mrbayes_mutation_map.RData')

all_stats_bayes <- matrix(nrow = 0, ncol = 3)
colnames(all_stats_bayes) <- c('id_num', 'FJ','FB')

for (i in 1:length(t)){
  ntree<-length(t[[i]])
  mm<-matrix(NA,nrow = ntree,ncol = 2) # FJ, FB
  for (j in 1:ntree){
    cid<-grep("^Consensus_",t[[i]][[j]]$tip.label)
    dists<-t2dist(t[[i]][[j]],cid) # FJ, FB
    mm[j,1:2]<-dists
  }
  all_stats_bayes <- rbind(all_stats_bayes, cbind(rep(i, ntree),mm))
}

bayes_dat <- enframe(s_df$aln_ids, name = 'id_num', value = 'id_orig') %>% 
  left_join(id_conversion) %>% 
  left_join(as_tibble(all_stats_bayes))
```

```{r bayes_summary}
bayes_dat %>% 
  group_by(id) %>% 
  summarize(n = n(),
            mean_fj = mean(FJ),
            sd_fj = sd(FJ),
            min_fj = min(FJ),
            max_fj = max(FJ)) 

bayes_dat %>% 
  group_by(id) %>% 
  summarize(n = n(),
            mean_fj = mean(FJ),
            sd_fj = sd(FJ),
            min_fj = min(FJ),
            max_fj = max(FJ)) %>% 
  ungroup() %>% 
  summarize(mean_mean = mean(mean_fj),
            mean_sd = mean(sd_fj))
```


```{r tree_plot_fn}
plot_tree_with_hist <- function(tree_list, data, metadat, tree_id_col = "tree_id", val_col = "distance") {
  
  # Calculate max years post-infection globally across all sets
  max_yr <- ceiling(max(as.numeric(unlist(strsplit(metadat$timepoints, '-'))), na.rm = TRUE)/365)
  
  # Loop through the names of the trees in your list
  plot_list <- lapply(names(tree_list), function(x) {
    
    # 1. Extract the current tree object
    tr <- tree_list[[x]]
    
    # 3. Custom visualization rooting override
    if(x == 'P5') {
      tr <- root(tr, tr$tip.label[grepl('AF138013', tr$tip.label)])
    }
    
    # 4. Filter metadata and merge/parse fields with separate_rows
    metadat_sub <- metadat %>% 
      filter(id == x)
    
    info <- tr %>% 
      as_tibble() %>%
      separate(label, sep = '\\_', remove = FALSE,
               into = c('patient_id', 'hxb2_start', 'hxb2_end', 'accession_number', 'subtype', 'days_from_infection', 'days_from_first_sample')) %>% 
      left_join(
        metadat_sub %>%
          mutate(timepoints = gsub('^-', 'neg', timepoints)) %>%
          separate_rows(c(timepoints, seq_in_timepoint), sep = '-') %>%
          separate_rows(seq_in_timepoint, sep = '\\+') %>%
          mutate(timepoints = as.numeric(gsub('neg', '-', timepoints)),
                 day = case_when(min(timepoints) < 0 ~ round(abs(min(timepoints)) + timepoints),
                                 TRUE ~ round(timepoints)),
                 year = day/365.25) %>%
          rename(timepoint = timepoints, accession_number = seq_in_timepoint),
        by = "accession_number"
      )
    
    labs <- c(ifelse(tr$tip.label == "Consensus_Subtype_B", "ref", NA), rep(NA, Nnode(tr)))
    
    # 5. Build the stylized ggtree plot using the processed metadata
    p_tree <- tr %>% 
      as_tibble() %>% 
      left_join(info) %>% 
      as.treedata() %>%
      ggtree() +
      geom_tippoint(aes(col = year, subset = isTip)) + # Fixed tip colors
      geom_tiplab(aes(label = labs), vjust = 0.25) + 
      scale_color_viridis_c(option = 'E', begin = 0, end = 1, breaks = breaks_pretty(), limits = c(0, max_yr), direction = -1, na.value = 'white') +
      labs(col = 'Years\npost-infection', title = x) + 
      theme(legend.position = 'none') +
      coord_cartesian(clip = "off")
    
    if(x == 'P8') {
    p_tree <- p_tree + geom_treescale(width = 0.05, offset = 5, x = 0.22, y = 100) #geom_treescale(width = 0.05, offset = 5)
    }
    
    # 6. DYNAMIC SCALE: Determine the maximum genetic distance of this SPECIFIC tree
    current_max_distance <- max(p_tree$data$x, na.rm = TRUE)
    
    # 7. Filter histogram dataframe for the current tree
    filtered_data <- data[data[[tree_id_col]] == x, ]
    
    # 8. Build the independent histogram with your explicit bin settings
    p_hist <- ggplot(filtered_data, aes(x = .data[[val_col]])) +
      geom_histogram(boundary = 0, binwidth = 0.005) + 
      theme_void() 
    
    # 9. Lock limits dynamically across both plots using scale_x_continuous + oob_keep
    p_tree_aligned <- p_tree + scale_x_continuous(limits = c(0, current_max_distance), oob = oob_keep)
    p_hist_aligned <- p_hist + scale_x_continuous(limits = c(0, current_max_distance), oob = oob_keep)
    
        # Define a shared margin so both plots keep their panels identical in size
    shared_margin <- margin(t = 5, r = 35, b = 5, l = 5, unit = "pt")

    # 9. Strip out redundant markings and apply the margin to the tree
    p_tree_aligned <- p_tree_aligned + 
      theme(axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            axis.title.x = element_blank(),
            plot.margin  = shared_margin) # Keeps tree bounds aligned
    
    # 10. Apply the exact same margin to the histogram
    p_hist_aligned <- p_hist_aligned +
      theme(plot.margin = shared_margin) # Keeps histogram bounds aligned
    
    # 11. Stack them neatly using patchwork framework
    combined_plot <- p_tree_aligned / p_hist_aligned + 
      plot_layout(heights = c(3, 1))

    # 12. RELATIVE WIDTH: Store a scaling factor width attribute directly in the plot object
    # For example, if a tree has a length of 0.2, its base width factor will evaluate smaller.
    # We add a baseline of 3 inches so tip labels still have room to breathe on small trees.
    attr(combined_plot, "plot_width") <- (current_max_distance * 15) + 3 
    
    return(combined_plot)
  })
  
  # Assign tree lookup IDs back onto the resulting output vector list
  names(plot_list) <- names(tree_list)
  return(plot_list)
}
```


```{r phylogenies, fig.width=13, fig.height=5}
# 1. Run your function (ensure it has legend.position = 'none' and shared_margin active)
tr_hists <- plot_tree_with_hist(trees_rooted, bayes_dat, metadat, 'id', 'FJ')

relative_widths <- sapply(tr_hists, function(p) attr(p, "plot_width"))

# 2. Split your list evenly into 2 rows as before
total_plots <- length(tr_hists)
midpoint <- ceiling(total_plots / 2)

row1_indices <- 1:midpoint
row1_plot <- wrap_plots(tr_hists[row1_indices]) + 
  plot_layout(ncol = length(row1_indices), widths = relative_widths[row1_indices])

row2_indices <- (midpoint + 1):total_plots
row2_plot <- wrap_plots(tr_hists[row2_indices]) + 
  plot_layout(ncol = length(row2_indices), widths = relative_widths[row2_indices])

# Combine the rows vertically
tree_rows <- row1_plot / row2_plot

# 3. FIX: Create a completely independent dummy plot just to grab its clean legend
max_yr <- ceiling(max(as.numeric(unlist(strsplit(metadat$timepoints, '-'))), na.rm = TRUE)/365)

dummy_legend_plot <- ggplot(data.frame(x = 1, y = 1, year = 0), aes(x = x, y = y, color = year)) +
  geom_point() +
  scale_color_viridis_c(
    option = 'E', begin = 0, end = 1, 
    breaks = breaks_pretty(), 
    limits = c(0, max_yr), 
    direction = -1, 
    na.value = 'white'
  ) +
  labs(color = 'Years\npost-infection') +
  theme_minimal() +
  theme(legend.position = "right")

# Extract just the legend element out of the dummy plot
pure_legend <- get_legend(dummy_legend_plot)

# 4. Stitch the legend onto the right side of your un-clipped rows
wrap_plots(tree_rows, pure_legend) + 
  plot_layout(ncol = 2, widths = c(1, 0.05))
```


```{r hiv_db_dists}
flt_con_aln <- read.dna('empirical_data/hiv_db_alns/HIV1_FLT_CON_2022_6225-7786_DNA_B.fasta', format = 'fasta')
flt_con_dists <- dist.dna(flt_con_aln, model = 'raw', pairwise.deletion = TRUE, as.matrix = TRUE)
flt_con_dists <- flt_con_dists['CON_B(1295)', colnames(flt_con_dists) != 'CON_B(1295)']
```

```{r}
quantile(flt_con_dists, 0.95)
max(dists_to_ref_real$dist)
```


```{r ref_dist_max, fig.width=10, fig.height=4}
ggarrange(slopes %>% 
  ggplot(aes(x = start_dist, y = slope)) +
  geom_point() +
  geom_smooth(span = 2, col = 'black') +
  stat_cor(method = 'spearman', cor.coef.name = "rho", label.x.npc = 0.6) +
  labs(x = 'Initial distance to\nreplicative reference', y = 'Rate of divergence from\nreplicative reference over time'),

enframe(flt_con_dists) %>% 
  separate(name, sep = '\\.', into = c('subtype', 'location', 'number', 'name', 'accession')) %>% 
  ggplot(aes(x = value)) +
  geom_histogram() +
  labs(x = 'Distance to replicative reference', y = 'Number of sequences'), labels = 'AUTO')
```

